### ISSUE TITLE
Network speeds seem incorrect sometimes

### ISSUE THREAD

**Issue by eliyen** [minhdanh/tmux-network-speed#2]
The displayed network speeds jump wildly sometimes, e.g. from 50 MB/s to 1 MB/s then back to 50 MB/s. This seems to happen when the status bar is [updated frequently](https://github.com/tmux/tmux/issues/797#issuecomment-282552872), leading me to suspect the network speeds are miscalculated if the status bar is updated more often than specified in the tmux status-interval setting. The tmux-net-speed plugin seems to have the same issue: https://github.com/tmux-plugins/tmux-net-speed/pull/13

**Comment by minhdanh** [comment]
Hi @eliyen, I've just updated the code to calculate the interval rather than relying on the maximum interval of tmux. Can you please try to update the plugin to see if problem still happens? The change is here: https://github.com/minhdanh/tmux-network-speed/commit/9db90cc1ed4647afa32e204dd150581ebcd9abf2

**Comment by eliyen** [comment]
I tested this on several downloads and it seems to have fixed the issue. I'm not seeing huge jumps in the displayed network speeds. Thanks for the fast fix!
